---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: pretty-format-json
      - id: mixed-line-ending
      - id: check-symlinks
        args: [--autofix]
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: meta
    hooks:
      - id: check-useless-excludes
